config/routes.rb
Rails.application.routes.draw do

  resources :users

  resources :orders

  resources :line_items

  resources :carts

  get 'store/index'

  resources :products

  get 'admin'=>'admin#index'

  controller :session do
    get 'login'=>:new
    post 'login'=>:create
    delete 'logout'=>:destroy
  end

  root :to=>'store#index', :as=>'store'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pragprog Books Online Store</title>
<!-- START:stylesheet -->
   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body id="store">
  <div id="banner">
    <%= image_tag("logo.png") %>
    <%= @page_title || "Pragmatic Bookshelf" %><!-- <label id="code.depot.e.title"/> -->
  </div>
  <div id="columns">
    <div id="side">
    <div id="cart">
    <%if @cart%>
      <%=hidden_div_if(@cart.line_items.empty?, :id=>"cart")  do%>
        <%=render @cart%>
      <%end%>
      <%end%>
    </div>
      <%=link("Home","index","store")%><br/>
      <a href="http://www..../faq">Questions</a><br />
      <a href="http://www..../news">News</a><br />
      <a href="http://www..../contact">Contact</a><br />
      <%if session[:user_id]%>
      <br/>
      <%=link_to 'Orders',orders_path%><br/>
      <%=link_to 'Products',products_path%> <br/>
      <%=link_to 'Users',users_path%> <br/>
      <br/>
      <%=button_to 'Logout',logout_path,:method=>:delete%>
      <%end%>
    </div>

    <div id="main">
      <%= yield %><!-- <label id="code.depot.e.include"/> -->
    </div>
  </div>
</body>
</html>